export enum Pages {
    DASHBOARD = "DASHBOARD",
    DEVICES = "DEVICES",
    ADD = "ADD",
    DELETE = "DELETE",
    UPDATE = "UPDATE",
    LIST = "LIST",
    LISTTEMP = "LISTTEMP",
    LISTHUM = "LISTHUM",
    LISTHIDRO = "LISTHIDRO",
    LISTLUZ = "LISTLUZ",
  }