export enum Pages {
    DASHBOARD = "DASHBOARD",
    DEVICES = "DEVICES",
    USERS = "USERS",
    LISTTEMP = "LISTTEMP",
    LISTHUM = "LISTHUM",
    LISTHIDRO = "LISTHIDRO",
    LISTLUZ = "LISTLUZ",
  }