export type CollectionNameType =
  | "TemperaturaSensor"
  | "HidrogenoSensor"
  | "LuzSensor"
  | "HumedadSensor"
  | "TemperaturaInterna"
  | "TemperaturaExterna"
  | "HumedadInterna"
  | "HumedadExterna"
  | "RadiacionUV"
  | "RadiacionSolar"
  | "Precipitaciones"
  | "PresionBarometricaRelativa"
  | "VelocidadViento"
  | "DireccionViento"
  | "Uv";
